[phases.setup]
nixPkgs = ["php", "phpExtensions.zip", "phpExtensions.pdo_mysql", "phpExtensions.mbstring", "phpExtensions.openssl", "phpExtensions.bcmath", "phpExtensions.curl", "composer"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --non-interactive",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]